import type { Donor, Hospital } from '@/types';

export const BLOOD_GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
export const ORGAN_TYPES = ['Kidney', 'Liver', 'Heart', 'Cornea', 'Lungs', 'Bone Marrow'];
export const CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai'];

// Mock Donors - 15+ donors across multiple blood groups and cities
export const mockDonors: Donor[] = [
  {
    id: 'donor_1',
    user_id: null,
    email: 'donor1@gmail.com',
    full_name: 'Rajesh Kumar',
    age: 28,
    blood_group: 'O+',
    city: 'Mumbai',
    phone: '9876543210',
    organs: ['Kidney', 'Liver', 'Cornea'],
    emergency_contact: '9876543211',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 250,
    blood_donations: 3,
    medical_allergies: 'Penicillin',
    medical_conditions: '',
    lat: 19.0760,
    lng: 72.8777,
    created_at: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'donor_2',
    user_id: null,
    email: 'donor2@gmail.com',
    full_name: 'Priya Sharma',
    age: 32,
    blood_group: 'A+',
    city: 'Mumbai',
    phone: '9876543220',
    organs: ['Kidney', 'Heart', 'Lungs'],
    emergency_contact: '9876543221',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 450,
    blood_donations: 5,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1136,
    lng: 72.8697,
    created_at: new Date('2023-06-20').toISOString(),
  },
  {
    id: 'donor_3',
    user_id: null,
    email: 'donor3@gmail.com',
    full_name: 'Amit Patel',
    age: 26,
    blood_group: 'B+',
    city: 'Delhi',
    phone: '9876543230',
    organs: ['Kidney', 'Liver', 'Bone Marrow'],
    emergency_contact: '9876543231',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 100,
    blood_donations: 1,
    medical_allergies: 'Sulfa',
    medical_conditions: '',
    lat: 28.7041,
    lng: 77.1025,
    created_at: new Date('2024-08-10').toISOString(),
  },
  {
    id: 'donor_4',
    user_id: null,
    email: 'donor4@gmail.com',
    full_name: 'Neha Singh',
    age: 24,
    blood_group: 'O-',
    city: 'Bangalore',
    phone: '9876543240',
    organs: ['Kidney', 'Liver', 'Heart', 'Cornea', 'Lungs', 'Bone Marrow'],
    emergency_contact: '9876543241',
    consent: true,
    available: true,
    donor_level: 'Platinum Lifesaver',
    donor_points: 800,
    blood_donations: 12,
    medical_allergies: '',
    medical_conditions: '',
    lat: 12.9716,
    lng: 77.5946,
    created_at: new Date('2022-03-05').toISOString(),
  },
  {
    id: 'donor_5',
    user_id: null,
    email: 'donor5@gmail.com',
    full_name: 'Vikram Das',
    age: 35,
    blood_group: 'AB+',
    city: 'Mumbai',
    phone: '9876543250',
    organs: ['Kidney', 'Liver'],
    emergency_contact: '9876543251',
    consent: true,
    available: false,
    donor_level: 'Silver',
    donor_points: 220,
    blood_donations: 4,
    medical_allergies: '',
    medical_conditions: 'Hypertension (controlled)',
    lat: 19.0176,
    lng: 72.8479,
    created_at: new Date('2023-11-12').toISOString(),
  },
  {
    id: 'donor_6',
    user_id: null,
    email: 'donor6@gmail.com',
    full_name: 'Ananya Gupta',
    age: 29,
    blood_group: 'B-',
    city: 'Delhi',
    phone: '9876543260',
    organs: ['Kidney', 'Cornea', 'Bone Marrow'],
    emergency_contact: '9876543261',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 550,
    blood_donations: 6,
    medical_allergies: 'Aspirin',
    medical_conditions: '',
    lat: 28.6139,
    lng: 77.2090,
    created_at: new Date('2023-02-28').toISOString(),
  },
  {
    id: 'donor_7',
    user_id: null,
    email: 'donor7@gmail.com',
    full_name: 'Ravi Menon',
    age: 31,
    blood_group: 'A-',
    city: 'Hyderabad',
    phone: '9876543270',
    organs: ['Kidney', 'Liver', 'Heart'],
    emergency_contact: '9876543271',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 300,
    blood_donations: 3,
    medical_allergies: '',
    medical_conditions: '',
    lat: 17.3850,
    lng: 78.4867,
    created_at: new Date('2024-04-19').toISOString(),
  },
  {
    id: 'donor_8',
    user_id: null,
    email: 'donor8@gmail.com',
    full_name: 'Deepa Reddy',
    age: 27,
    blood_group: 'O+',
    city: 'Chennai',
    phone: '9876543280',
    organs: ['Kidney', 'Liver', 'Cornea', 'Bone Marrow'],
    emergency_contact: '9876543281',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 480,
    blood_donations: 8,
    medical_allergies: '',
    medical_conditions: '',
    lat: 13.0827,
    lng: 80.2707,
    created_at: new Date('2023-09-03').toISOString(),
  },
  {
    id: 'donor_9',
    user_id: null,
    email: 'donor9@gmail.com',
    full_name: 'Sanjay Iyer',
    age: 33,
    blood_group: 'AB-',
    city: 'Bangalore',
    phone: '9876543290',
    organs: ['Liver', 'Heart'],
    emergency_contact: '9876543291',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 150,
    blood_donations: 2,
    medical_allergies: '',
    medical_conditions: '',
    lat: 12.9352,
    lng: 77.6245,
    created_at: new Date('2024-07-22').toISOString(),
  },
  {
    id: 'donor_10',
    user_id: null,
    email: 'donor10@gmail.com',
    full_name: 'Kavya Nair',
    age: 25,
    blood_group: 'B+',
    city: 'Mumbai',
    phone: '9876543300',
    organs: ['Kidney', 'Liver', 'Lungs', 'Bone Marrow'],
    emergency_contact: '9876543301',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 420,
    blood_donations: 7,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1808,
    lng: 72.9694,
    created_at: new Date('2023-05-14').toISOString(),
  },
  {
    id: 'donor_11',
    user_id: null,
    email: 'donor11@gmail.com',
    full_name: 'Arjun Verma',
    age: 30,
    blood_group: 'O+',
    city: 'Delhi',
    phone: '9876543310',
    organs: ['Kidney', 'Heart', 'Cornea'],
    emergency_contact: '9876543311',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 280,
    blood_donations: 4,
    medical_allergies: 'Latex',
    medical_conditions: '',
    lat: 28.5244,
    lng: 77.1855,
    created_at: new Date('2024-02-08').toISOString(),
  },
  {
    id: 'donor_12',
    user_id: null,
    email: 'donor12@gmail.com',
    full_name: 'Swati Desai',
    age: 28,
    blood_group: 'A+',
    city: 'Hyderabad',
    phone: '9876543320',
    organs: ['Kidney', 'Liver', 'Bone Marrow'],
    emergency_contact: '9876543321',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 500,
    blood_donations: 9,
    medical_allergies: '',
    medical_conditions: '',
    lat: 17.4065,
    lng: 78.4772,
    created_at: new Date('2023-07-17').toISOString(),
  },
  {
    id: 'donor_13',
    user_id: null,
    email: 'donor13@gmail.com',
    full_name: 'Mohit Kumar',
    age: 26,
    blood_group: 'B-',
    city: 'Bangalore',
    phone: '9876543330',
    organs: ['Kidney', 'Liver'],
    emergency_contact: '9876543331',
    consent: true,
    available: true,
    donor_level: 'Bronze',
    donor_points: 120,
    blood_donations: 1,
    medical_allergies: '',
    medical_conditions: '',
    lat: 12.9450,
    lng: 77.5710,
    created_at: new Date('2024-08-25').toISOString(),
  },
  {
    id: 'donor_14',
    user_id: null,
    email: 'donor14@gmail.com',
    full_name: 'Priyanka Chopra',
    age: 34,
    blood_group: 'O+',
    city: 'Chennai',
    phone: '9876543340',
    organs: ['Kidney', 'Heart', 'Lungs'],
    emergency_contact: '9876543341',
    consent: true,
    available: true,
    donor_level: 'Silver',
    donor_points: 320,
    blood_donations: 5,
    medical_allergies: '',
    medical_conditions: '',
    lat: 13.0897,
    lng: 80.2740,
    created_at: new Date('2023-12-01').toISOString(),
  },
  {
    id: 'donor_15',
    user_id: null,
    email: 'donor15@gmail.com',
    full_name: 'Akshay Bhat',
    age: 29,
    blood_group: 'AB+',
    city: 'Mumbai',
    phone: '9876543350',
    organs: ['Liver', 'Heart', 'Bone Marrow'],
    emergency_contact: '9876543351',
    consent: true,
    available: true,
    donor_level: 'Gold',
    donor_points: 460,
    blood_donations: 7,
    medical_allergies: '',
    medical_conditions: '',
    lat: 19.1344,
    lng: 72.9193,
    created_at: new Date('2023-10-09').toISOString(),
  },
];

// Mock Hospitals - 3 hospitals across 2 cities
export const mockHospitals: Hospital[] = [
  {
    id: 'hospital_1',
    user_id: null,
    email: 'apollo@gmail.com',
    hospital_name: 'Apollo Hospital Mumbai',
    registration_id: 'REG-001-MH',
    city: 'Mumbai',
    address: 'Bandra, Mumbai',
    contact_person: 'Dr. Amit Sanyal',
    phone: '9876543100',
    verified: true,
    lat: 19.0596,
    lng: 72.8295,
    inventory: {
      'O+': 10,
      'O-': 5,
      'A+': 8,
      'B+': 6,
      'AB+': 3,
      'Kidney': 2,
      'Liver': 1,
      'Heart': 1,
    },
    created_at: new Date('2020-01-15').toISOString(),
  },
  {
    id: 'hospital_2',
    user_id: null,
    email: 'fortis@gmail.com',
    hospital_name: 'Fortis Delhi',
    registration_id: 'REG-002-DL',
    city: 'Delhi',
    address: 'Okhla, Delhi',
    contact_person: 'Dr. Sharma',
    phone: '9876543101',
    verified: true,
    lat: 28.5499,
    lng: 77.2364,
    inventory: {
      'O+': 12,
      'O-': 4,
      'A+': 7,
      'B+': 8,
      'AB+': 2,
      'Kidney': 3,
      'Liver': 2,
      'Heart': 0,
    },
    created_at: new Date('2020-06-20').toISOString(),
  },
  {
    id: 'hospital_3',
    user_id: null,
    email: 'manipal@gmail.com',
    hospital_name: 'Manipal Hospital Bangalore',
    registration_id: 'REG-003-KA',
    city: 'Bangalore',
    address: 'HAL Airport, Bangalore',
    contact_person: 'Dr. Patel',
    phone: '9876543102',
    verified: true,
    lat: 12.9699,
    lng: 77.7499,
    inventory: {
      'O+': 9,
      'O-': 3,
      'A+': 6,
      'B+': 7,
      'AB+': 1,
      'Kidney': 4,
      'Liver': 1,
      'Heart': 2,
    },
    created_at: new Date('2021-03-10').toISOString(),
  },
];

// Stats for landing page
export const LANDING_STATS = {
  lives_saved: 1250,
  active_donors: 15000,
  hospitals_connected: 150,
  cities_covered: 8,
};

// Testimonials
export const TESTIMONIALS = [
  {
    name: 'Rajesh Patel',
    role: 'Organ Recipient',
    city: 'Mumbai',
    message: 'LifeLink saved my life. Within 48 hours of my emergency call, a perfect kidney match was found.',
    image: '👨‍⚕️',
  },
  {
    name: 'Priya Sharma',
    role: 'Blood Donor',
    city: 'Delhi',
    message: 'Being part of LifeLink gives me purpose. Knowing my donations help save lives is incredibly fulfilling.',
    image: '👩‍⚕️',
  },
  {
    name: 'Dr. Arvind Singh',
    role: 'Hospital Director',
    city: 'Bangalore',
    message: 'The matching algorithm is brilliant. We reduced emergency response time by 40%.',
    image: '👨‍💼',
  },
];
